sudo: required
services: 
  - docker

before_install:
  - docker build -t sisyphuss10/docker-reactapp -f Dockerfile.dev .

script:
  - docker run sisyphuss10/docker-reactapp npm run test -- --coverage